apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: email-service
  namespace: s65-2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: email-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75