name: .NET Core pull_request on develop branch

on:
  pull_request:
    branches: [develop]

env:
  PROJECT_NAME: EmailMicroservice
  DOCKER_ORGANIZATION: s652
  DOCKER_REPOSITORY: email-service

jobs:
  build:
    # The virtual machine that will be used on GitHub
    runs-on: ubuntu-18.04
    
    # Run the steps in a Docker container on the virtual machine
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1.201-bionic
    
    steps:
      # Checkout Git repository
      - uses: actions/checkout@v2

      # Decrypt the GPG encrypted config files
      - name: Decrypt the GPG encrypted config files
        run: gpg --quiet --batch --yes --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output ./${{ env.PROJECT_NAME }}/appsettings.json --decrypt ./${{ env.PROJECT_NAME }}/appsettings.json.gpg

      # Install the dependencies needed for the project
      - name: Install dependencies
        run: dotnet restore
      
      # Build the project
      - name: Build
        run: dotnet build
      
      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Sonarscanner for dotnet
        uses: Secbyte/dotnet-sonarscanner@v2.3
        with:
          buildCommand: dotnet build .
          testCommand: dotnet test .
          projectKey: S65-2-project_EmailMicroservice
          projectName: EmailMicroservice
          sonarOrganisation: s65-2-project
          beginArguments: >
              /d:sonar.verbose="true"
              /d:sonar.cs.opencover.reportsPaths='"/path/to/coverage.xml","/path/to/coverage.2.xml"'
              /d:sonar.coverage.exclusions='"**/*.cs","**/*.md","sonar-project.properties"'
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}