name: .NET Core push on master branch

on:
  push:
    branches: [feature/*]
    tags:
      - '**'

env:
  DOCKER_ORGANIZATION: s652
  DOCKER_REPOSITORY: email-service
  DOCKER_IMAGE: s652/email-service:${{ github.sha }}
  DOCKER_IMAGE_LATEST: s652/email-service:latest
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: s65-2
  GKE_ZONE: europe-west4-a
  GKE_NAMESPACE: s65-2

jobs:
  build:
    # The virtual machine that will be used on GitHub
    runs-on: ubuntu-18.04
    
    # Run the steps in a Docker container on the virtual machine
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1.201-bionic
    steps:
      # Checkout Git repository
      - uses: actions/checkout@v2

      # Decrypt the GPG encrypted config files
      - name: Decrypt the GPG encrypted config files
        run: gpg --quiet --batch --yes --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output ./EmailMicroservice/appsettings.json --decrypt ./EmailMicroservice/appsettings.json.gpg

      # Install the dependencies needed for the project
      - name: Install dependencies
        run: dotnet restore
      
      # Build the project
      - name: Build
        run: dotnet build
      
      # Test the project
      - name: Test
        run: dotnet test
      
      # Publish the release build in the /release folder
      - name: Publish
        run: dotnet publish -c Release -o release
      
      # Upload the release folder, Dockerfile and Kubernetes artifacts to this GitHub workflow for use in the next job
      - name: Upload release artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-artifact
          path: ./release

      - name: Upload Dockerfile artifact
        uses: actions/upload-artifact@v1
        with:
          name: dockerfile-artifact
          path: ./Dockerfile

      - name: Upload Kubernetes artifact
        uses: actions/upload-artifact@v1
        with:
          name: kubernetes-artifact
          path: ./kube
  
  deliver:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      # Download artifacts from GitHub workflow to use in this job
      - name: Download release artifact
        uses: actions/download-artifact@v1
        with:
          name: release-artifact
          path: ./release
      - name: Download Dockerfile artifact
        uses: actions/download-artifact@v1
        with:
          name: dockerfile-artifact
          path: .
      
      # Deliver Docker image to DockerHub
      - name: Deliver Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker build -t $DOCKER_IMAGE -t $DOCKER_IMAGE_LATEST .
          docker push $DOCKER_IMAGE
          docker push $DOCKER_IMAGE_LATEST
  
  deploy:
    needs: deliver
    runs-on: ubuntu-18.04
    steps:
      - name: Download Kubernetes artifact
        uses: actions/download-artifact@v1
        with:
          name: kubernetes-artifact
          path: ./kube

      # Setup connection with the gcloud CLI
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}

      # Get GKE cluster credentials
      - name: Get GKE cluster credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

      # Deploy to GKE cluster
      - name: Deploy to GKE clusters
        run: |
          kubectl apply \
            -f ./kube/autoscaler.yaml \
            -f ./kube/deployment.yaml \
            -f ./kube/service.yaml
          kubectl set image Deployment/$DOCKER_REPOSITORY --namespace $GKE_NAMESPACE $DOCKER_REPOSITORY=$DOCKER_IMAGE
          kubectl rollout status Deployment/$DOCKER_REPOSITORY --namespace $GKE_NAMESPACE
          kubectl get services -o wide
        
      # - name: Setup Kubectl
      #   uses: azure/setup-kubectl@v1

      # - name: Set context via kubeconfig
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     method: kubeconfig
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}
        
      # - name: Deploy Kubernetes with manifests
      #   uses: azure/k8s-deploy@v1
      #   with:
      #     namespace: $GKE_NAMESPACE
      #     manifests: |
      #       ./kube/autoscaler.yaml
      #       ./kube/deployment.yaml
      #       ./kube/service.yaml
      #     images: |
      #       $DOCKER_ORGANIZATION/$DOCKER_REPOSITORY:${{ github.sha }}
      